# https://github.com/Dreamacro/clash/wiki/Configuration
# https://github.com/Loyalsoldier/clash-rules

mixed-port: 7890
allow-lan: false
mode: rule
log-level: silent
external-controller: 127.0.0.1:9090

rules:
  - MATCH, Proxy

proxy-groups:
  - name: Proxy
    type: select
    use:
      - "Proxy-Provider"

proxy-providers:
  Proxy-Provider:
    type: file
    path: ./proxy-provider.yaml
